image: python:3.9

stages:
  - test

job_testing:
  stage: test
  script:
    - pip install -r requirements.txt  # Install requirements
    - pylint *.py                      # Analitzador est√†tic
    - coverage run test.py             # Executar tests amb coverage
    - coverage report                  # Mostrar resultats
